### ISSUE TITLE
ReferenceError starting CKEditor

### ISSUE THREAD

**Issue by init7k** [w8tcha/CKEditor-AutoSave-Plugin#66]
Using version 0.13 everything works fine. 
Upgraded to version 0.15 getting "ReferenceError: editorInstance is not defined" on line 31 of plugin.js.

**Comment by w8tcha** [comment]
try the updated plugin.js from the source repository, i already fixed the bug

**Comment by init7k** [comment]
Sorry, but the only line differs from my version to that of the repository is line 13 lang:....
Problem still persists.

**Comment by w8tcha** [comment]
i forgot to commit one change

**Comment by init7k** [comment]
Thanks, error on startup is gone, editor is displayed.
But another error occures when writing to editor: 
ReferenceError: event is not defined on line 105.

**Comment by w8tcha** [comment]
okay fixed

**Comment by init7k** [comment]
Where to find the new code with changes?

**Comment by w8tcha** [comment]
sorry now the commit is online
